spring:
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost/meetings
    username: meetings
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      hiberate:
        SQL: debug
      type:
        descriptor:
          sql: trace
flyway:
  enabled: true
security:
  user:
    name: user
    password: password
